BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "usuario" (
	"id_usr"	INTEGER,
	"usuario"	VARCHAR(100) NOT NULL,
	"login"	VARCHAR(30) NOT NULL,
	"pass"	VARCHAR(100) NOT NULL,
	"id_grp"	INTEGER NOT NULL,
	PRIMARY KEY("id_usr" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "grupo" (
	"id_grp"	INTEGER,
	"grupo"	VARCHAR(30) NOT NULL,
	PRIMARY KEY("id_grp" AUTOINCREMENT)
);
COMMIT;
